# Refer to MDK and documentation for details
modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://github.com/LemADEC/WarpDrive/issues"
showAsResourcePack=false

[[mods]]
  modId="warpdrive"
  version="${mod_version}"
  displayName="WarpDrive"
  #updateJSONURL="minecraftforge.net/versions.json"
  displayURL="http://minecraft.curseforge.com/projects/warpdrive"
  logoFile="logo.png"
  credits="Original concept and implementation by Cr0s, modified by ZLOFENIX, DarkholmeTenk & drpepper240. Merged, bugfixed and ported to WWM by LemADEC."
  authors="LemADEC, Cr0s, DarkholmeTenk, drpepper240, ZLOFENIX"
  description='''
  Create your own space ship from any blocks (excluding bedrock) and sail it trough space.
  Explore the space dimension: asteroids (filled with ores), asteroid fields, gas clouds, planetoids, stars, and NPC-ships.
  Jump to hyperspace for long-range traveling!
  Set up laser cannons on your ship to fight with other players' ships, or craft a mining laser to collect valuable resources on Earth or in space.
  Cloak your ship, base or a space station from your enemies!
  And lots more!
  '''
  
  [[dependencies.warpdrive]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.warpdrive]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"
    
  [[dependencies.warpdrive]]
    modId="computercraft"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
    
  [[dependencies.warpdrive]]
    modId="enderio"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
    
  [[dependencies.warpdrive]]
    modId="gregtech"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
    
  [[dependencies.warpdrive]]
    modId="ic2"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
    
  [[dependencies.warpdrive]]
    modId="icbmclassic"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
    
  [[dependencies.warpdrive]]
    modId="opencomputers"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
    